# Generated by Django 5.0 on 2023-12-27 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_name', models.CharField(max_length=10, null=True)),
                ('student_regno', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub1_rank', models.FloatField(max_length=4, null=True)),
                ('sub2_rank', models.FloatField(max_length=4, null=True)),
                ('sub3_rank', models.FloatField(max_length=4, null=True)),
                ('student_regno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsquare.student')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark1', models.IntegerField(default=0)),
                ('mark2', models.IntegerField(default=0)),
                ('mark3', models.IntegerField(default=0)),
                ('regno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsquare.student')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub1_grade', models.CharField(max_length=2)),
                ('sub2_grade', models.CharField(max_length=2)),
                ('sub3_grade', models.CharField(max_length=2)),
                ('reg_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsquare.student')),
            ],
        ),
        migrations.CreateModel(
            name='EditMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=3)),
                ('regno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsquare.student')),
            ],
        ),
    ]
